#!/bin/bash
# Takes an application name

if [ $# -ne 1 ]; then
   echo "Please provide a component name"
   exit 1
fi

name=$1

cd `echo $0 | sed 's#/[A-Za-z0-9]*$##'`

if test -e ../components/${name}.st; then
   sleep 0
else
   echo "Couldn't find file ${name}.st to component ${name}"
   exit 1
fi

saveLine=`grep "ObjectMemory snapshot:" ../components/${name}.st | tr \' \€`
if test -z "$saveLine"; then
   echo "Couldn't find snapshot line - please make sure your file saves the image somewhere using \"ObjectMemory snapshot: 'FILENAME.im'\""
   exit 1
fi

quotedName=`echo \'$name\' | tr \' \€`

eval "/bin/sed -i 's/ObjectMemory snapshot.*$/$name registerAsApplication: $quotedName.\n$saveLine\n/' ../components/${name}.st"
cat ../components/${name}.st | tr \€ \' > ${name}.st
mv ${name}.st ../components/
